### ISSUE TITLE
PyPI Registration

### ISSUE THREAD

**Issue by muhuk** [seveas/django-echelon#1]
Would you consider registering this app with [PyPI](http://pypi.python.org/pypi)?

Here is [an how-to](http://guide.python-distribute.org/contributing.html). I would be happy to help if I can.

**Comment by seveas** [comment]
I might do that when I've updated it to work with 1.3

**Comment by muhuk** [comment]
I have tested with 1.3 and it works fine.

**Comment by seveas** [comment]
I've now registered it after adding the second part of echelon: automated change logging.

**Comment by muhuk** [comment]
Thank you very much.

**Comment by muhuk** [comment]
Could you possibly upload a source package too? Otherwise we still have to install from the repository.

```
python setup.py sdist upload
```

should do.
