### ISSUE TITLE
Anonymous does not have pk field

### ISSUE THREAD

**Issue by renzcoldsun** [seveas/django-echelon#4]
In django 1.4, this error shows up. 

I don't know the repercussion of this patch, but will this do?

```
diff -ru1 echelon/fields.py echelona/fields.py
--- echelon/fields.py   2013-03-18 10:14:26.805418317 +0800
+++ echelona/fields.py  2013-03-18 10:14:03.241566328 +0800
@@ -66,4 +66,4 @@
             if user:
-                setattr(model_instance, self.attname, user.pk)
-                return user.pk
+                setattr(model_instance, self.attname, user.id)
+                return user.id
         return super(CurrentUserField, self).pre_save(model_instance, add)
```

**Comment by seveas** [comment]
Hmm, that's bizarre. `pk` should be an alias for the primary key. Are you saying that in 1.4, `User` doesn't have a primary key?

**Comment by renzcoldsun** [comment]
Really bizarre. I use .pk in my views everytime. But still the patch works.

**Comment by seveas** [comment]
Release 1.2, just pushed to github and the cheeseshop, fixes this in a better way.
